Repository wcus/wcus-2019, pull requests merged in 2019-05, with the labels that each got.

#38 setting up ticket table styles
  package-lock.json
  sass/abstracts/_structure.scss
  sass/elements/_tables.scss
  sass/forms/_fields.scss
  sass/modules/_alignments.scss
  sass/site/_site.scss
  sass/site/primary/_tickets.scss
  style.css
Labels: [status] needs review

#45 Add `has-fancy-list` style for stylized homepage list
  sass/elements/blocks/_blocks.scss
  sass/elements/blocks/_list.scss
  style.css
Labels: [status] needs review

#46 quick fix to get the title aligned with content on archive pages.
  sass/site/primary/_posts-and-pages.scss
  style.css
Labels: [status] needs review

#51 Fix the line height & indentation of radio/inputs in ticket form
  sass/elements/_tables.scss
  sass/site/primary/_tickets.scss
  style.css
Labels: [status] needs review

#52 switching mobile ticket page to display block for stacking.
  sass/site/primary/_tickets.scss
  style.css
Labels: [status] needs review

#63 Ticket page tweaks
  sass/site/primary/_tickets.scss
  style.css
Labels: [status] needs review

#69 Tighten space in primary navigation
  assets/chevron-down-current.svg
  assets/chevron-down-hover.svg
  assets/chevron-down.svg
  sass/abstracts/_assets.scss
  sass/navigation/_menus.scss
  style.css
Labels: [status] needs review

#70 Style archive pages & 404 page
  sass/abstracts/_mixins-utilities.scss
  sass/site/_site.scss
  sass/site/primary/_404.scss
  sass/site/primary/_posts-and-pages.scss
  style.css
Labels: [status] needs design review

#72 Add a colors table to the theme readme
  README.md
Labels: [status] in progress

#73 Update/header small screen
  assets/bottom-wave.svg
  assets/logo-black-small.png
  sass/abstracts/_assets.scss
  sass/abstracts/_structure.scss
  sass/layout/_content.scss
  sass/navigation/_menus.scss
  sass/site/secondary/_header-hero.scss
  sass/site/secondary/_home-info.scss
  style.css
Labels: [status] needs review

#75 Customizer fixes
  sass/abstracts/_typography.scss
  sass/elements/_lists.scss
  sass/elements/_tables.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_tickets.scss
  style.css
Labels: [status] needs review

#74 Switch the breakpoint for homepage widgets
  sass/site/secondary/_home-info.scss
  style.css
Labels: [status] needs review

#78 Add the organizers page style
  sass/site/_site.scss
  sass/site/primary/_organizers.scss
  style.css
Labels: [status] needs review

#79 Move over Customizer CSS
  sass/forms/_fields.scss
  sass/site/primary/_posts-and-pages.scss
  sass/site/primary/_tickets.scss
  sass/site/secondary/_subscribe.scss
  style.css
Labels: [status] needs review
