Repository wcus/wcus-2019, pull requests merged in 2019-04, with the labels that each got.

#8 Add style for page header: logo & main navigation
  assets/arrow-down-current.svg
  assets/arrow-down-hover.svg
  assets/arrow-down.svg
  assets/pencil.svg
  assets/underline-current.svg
  assets/underline-hover.svg
  sass/abstracts/_abstract.scss
  sass/abstracts/_assets.scss
  sass/abstracts/_mixins-fonts.scss
  sass/abstracts/_structure.scss
  sass/layout/_content.scss
  sass/navigation/_menus.scss
  style.css
Labels: [status] needs design review, [status] needs review

#11 Update base styles– colors & buttons
  sass/abstracts/_colors.scss
  sass/abstracts/_mixins-fonts.scss
  sass/elements/_blocks.scss
  sass/layout/_content.scss
  sass/navigation/_links.scss
  sass/navigation/_menus.scss
  sass/typography/_copy.scss
  sass/typography/_headings.scss
  style.css
Labels: [status] needs design review, [status] needs review

#21 updating SVGs to new domain
  sass/abstracts/_assets.scss
  style.css
Labels: [status] needs review

#13 Add Sponsors style
  sass/layout/_content.scss
  sass/site/_site.scss
  sass/site/primary/_sponsors.scss
  sass/site/secondary/_footer.scss
  sass/site/secondary/_widgets.scss
  style.css
Labels: [status] needs design review, [status] needs review

#22 adding in the dot separator
  assets/Separator-Dots-Sparkles.svg
  assets/Separator-Wide-Sparkles.svg
  assets/border-dot.svg
  sass/abstracts/_assets.scss
  sass/elements/_blocks.scss
  style.css
Labels: [status] needs design review, [status] needs review

#12 Interior page
  assets/short-wave.svg
  package-lock.json
  sass/abstracts/_assets.scss
  sass/abstracts/_structure.scss
  sass/abstracts/_typography.scss
  sass/modules/_alignments.scss
  sass/site/primary/_posts-and-pages.scss
  style.css
Labels: [status] needs design review

#25 setting up latest posts block
  sass/abstracts/_structure.scss
  sass/elements/_blocks.scss
  sass/elements/_latest-posts.scss
  style.css
Labels: [status] needs review

#33 Style Media & Text block
  sass/elements/_elements.scss
  sass/elements/blocks/_blocks.scss
  sass/elements/blocks/_latest-posts.scss
  sass/elements/blocks/_media-text.scss
  style.css
Labels: [status] needs review

#31 Update color classes to use our colors
  sass/elements/_colors.scss
  sass/elements/_elements.scss
  sass/elements/blocks/_blocks.scss
  sass/elements/blocks/_latest-posts.scss
  sass/elements/blocks/_media-text.scss
  style.css
Labels: [status] needs review

#32 Style Cover block
  sass/abstracts/_mixins-fonts.scss
  sass/abstracts/_structure.scss
  sass/elements/blocks/_blocks.scss
  sass/forms/_fields.scss
  style.css
Labels: [status] needs review

#35 Style quote blocks: pullquote, 2 styles of blockquote
  sass/abstracts/_assets.scss
  sass/abstracts/_colors.scss
  sass/elements/blocks/_blockquote.scss
  sass/elements/blocks/_blocks.scss
  sass/elements/blocks/_pullquote.scss
  style.css
Labels: [status] needs review

#37 Add a custom style “header” for media & text block
  sass/elements/blocks/_media-text.scss
  style.css
Labels: [status] needs review

#27 Homepage header + widgets
  assets/bottom-wave.svg
  assets/logo-badge.svg
  assets/pencil.svg
  assets/wcus-background-white.jpg
  assets/wcus-background.jpg
  sass/abstracts/_assets.scss
  sass/layout/_content.scss
  sass/site/secondary/_header-hero.scss
  sass/site/secondary/_widgets.scss
  style.css
Labels: [status] needs review

#30 Style homepage widgets
  sass/abstracts/_mixins-fonts.scss
  sass/abstracts/_mixins-utilities.scss
  sass/forms/_fields.scss
  sass/site/primary/_sponsors.scss
  sass/site/secondary/_header-hero.scss
  sass/site/secondary/_home-info.scss
  sass/site/secondary/_subscribe.scss
  sass/site/secondary/_widgets.scss
  style.css
Labels: [status] needs design review, [status] needs review

#39 Style the image & gallery blocks
  sass/elements/_elements.scss
  sass/elements/blocks/_blocks.scss
  style.css
Labels: [status] needs review

#42 Add single post styles
  assets/arrow-left.svg
  assets/pale-brown-dots.svg
  assets/separator-short-wide.svg
  assets/tag.svg
  sass/abstracts/_assets.scss
  sass/navigation/_menus.scss
  sass/site/primary/_comments.scss
  sass/site/primary/_posts-and-pages.scss
  style.css
Labels: [status] needs review

#41 Update google maps shortcode to use alignwide style
  sass/elements/blocks/_blocks.scss
  style.css
Labels: [status] needs review

#40 Tweak separator spacing & style
  assets/pale-blue-dots-dense.svg
  sass/abstracts/_assets.scss
  sass/elements/blocks/_blocks.scss
  sass/site/secondary/_home-info.scss
  style.css
Labels: [status] needs review

#43 Update spacing on alignwide blocks on small screens
  sass/elements/blocks/_latest-posts.scss
  sass/modules/_alignments.scss
  style.css
Labels: [status] needs review
